

default:
	(cd METISLib ; make ) 
	(cd ParMETISLib ; make ) 
#	(cd Programs ; make ) 

	cp -f parmetis.h ../include
clean:
	(cd METISLib ; make realclean )
	(cd ParMETISLib ; make realclean )
	(cd Programs ; make realclean )


